const number1 = 10;
const number2 = 11;
const product = number1 * number2;
console.log(product);
console.log(typeof product);
const charge = 35.99;
const payment = 20;
const amountRemaining = charge - payment;
console.log(amountRemaining);
console.log(typeof amountRemaining);
const tests = 50;
const assignments = 20;
const final = 40;
const grade = (tests + assignments + final) / 3;
console.log(grade);
console.log(typeof grade);
const firstName = 'Eli';
const lastName = 'Bales';
const fullName = firstName + ' ' + lastName;
console.log(fullName);
console.log(typeof fullName);
const pH = 2;
const isAcidic = pH < 7;
console.log(isAcidic);
console.log(typeof isAcidic);
const numberOfSoldiers = 299;
const isSparta = numberOfSoldiers === 300;
console.log(isSparta);
console.log(typeof isSparta);
let nickname = fullName;
nickname += ' is the GOAT';
console.log(nickname);
console.log(typeof nickname);
